name: Publish Angular Library to npm

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Build Angular library
        run: npm run build-library

      - name: Remove repository field from package.json
        run: |
          cd dist/ngx-otp-code-input
          node -e "const pkg=require('./package.json'); delete pkg.repository; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"

      - name: Publish to npm
        run: npm publish dist/ngx-otp-code-input --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}